import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/auth/AuthProvider";
import ToastContainer from "@/components/atoms/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
